# Generated by Django 5.2.5 on 2025-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_featured_image_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
